### PR TITLE
Initial implementation of a database status manager

### PR DESCRIPTION
**Pull request by kezike**
This PR addresses https://github.com/digitalcredentials/credential-status-manager-git/issues/22, by adding support for a database status manager.

### CODE REVIEW

**Review by jchartrand — APPROVED** [review]
Looks great! Amazingly comprehensive error checking.

**Comment by dmitrizagidulin** [comment]
PR looks good, though please use jsdoc style function comments (instead of the current `//` style).

**Comment by alexfigtree** [comment]
This PR is waiting on changes from @jchartrand and should not be merged yet.

**Comment by alexfigtree** [comment]
Done, closing

**Pull request merged**
